### ISSUE TITLE
400 The SSL certificate error

### ISSUE THREAD

**Issue by Agachily** [lunarway/openbanking#31]
Hi,

I am trying to register with Lunar with our company's certificate, which is issued by Finnish Financial Supervisory Authority. However, I kept on facing the error stating that our SSL certificate is invalid. Detailed response is as follows:
`
{"result": {"status": 400, "response": "<html>\\r\\n<head><title>400 The SSL certificate error</title></head>\\r\\n<body>\\r\\n<center><h1>400 Bad Request</h1></center>\\r\\n<center>The SSL certificate error</center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n", "headers": [["Date", "Fri, 13 May 2022 07:10:56 GMT"], ["Content-Type", "text/html"], ["Content-Length", "208"], ["Connection", "close"]]}}
`

The latest request is made at 10.21 Friday, 13 May 2022 (EEST) with the X-Request-Id `1e1a81b2-5e42-4d52-b1f0-80377ae78662`.

The certificate I used is as follows:
```
-----BEGIN CERTIFICATE-----
MIIK8DCCCdigAwIBAgIOAYK/rawhJ0XopEOq0AowDQYJKoZIhvcNAQELBQAwejEL
MAkGA1UEBhMCSFUxETAPBgNVBAcMCEJ1ZGFwZXN0MRYwFAYDVQQKDA1NaWNyb3Nl
YyBMdGQuMRcwFQYDVQRhDA5WQVRIVS0yMzU4NDQ5NzEnMCUGA1UEAwweUXVhbGlm
aWVkIGUtU3ppZ25vIFRMUyBDQSAyMDE4MB4XDTIwMDcyMDEzMjYzNFoXDTIyMDcy
MDEzMjYzNFowgb4xEzARBgsrBgEEAYI3PAIBAxMCRkkxHTAbBgNVBA8MFFByaXZh
dGUgT3JnYW5pemF0aW9uMRIwEAYDVQQFEwkyOTg4NDk5LTcxCzAJBgNVBAYTAkZJ
MQ4wDAYDVQQHDAVFc3BvbzEaMBgGA1UECgwRRW5hYmxlIEJhbmtpbmcgT3kxHzAd
BgNVBGEMFlBTREZJLUZJTkZTQS0yOTg4NDk5LTcxGjAYBgNVBAMMEWVuYWJsZWJh
bmtpbmcuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAscnbTyQn
hEDKr+zPUw5qVBWr+R+uCYVlVAQDULCRs6xvK3sk1ClFVe5OvkclG11EcTPqrx64
KXDzb8mYezfr3NORXA83yaleWIf9p1/RbdK7fpRqmP6WP4gicZFRmZzGe5wLBSll
sieBVMxT3OGP4OomV4ewv6grIzry/C4wrdw3swPZMC4T49f+6Tj4yV+/zKRUH8jw
/PaJl5tS6yTZzQCtPsf1jJnllIdYP9sl/usnU9aLdDTXcbJmBTUN+j3HB2MIEDtf
xorV5RtF5kmAacjlsyIrTZStymVXvLhB2c/qm2PxRWBrWs6o8Z3cBWGsFXlpkSa4
qME7h82heyR3KwIDAQABo4IHLTCCBykwDgYDVR0PAQH/BAQDAgWgMIIBgAYKKwYB
BAHWeQIEAgSCAXAEggFsAWoAdwApeb7wnjk5IfBWc59jpXflvld9nGAK+PlNXSZc
JV3HhAAAAXNsZ5khAAAEAwBIMEYCIQDPjmtH/hDKEHRw5+KPuhF1psA3X6fwBQZv
vUIcsVweiwIhAM2RjiQCy/N2SAj6ZU3AMA9aZsehWwXon1R6cyV/EZtzAHcAVYHU
whaQNgFK6gubVzxT8MDkOHhwJQgXL6OqHQcT0wwAAAFzbGebxgAABAMASDBGAiEA
wEnVHBUN6S30JNDHzhopCTGJOBG802OahYacgK1V2yoCIQDl9W3VuYrHLgfLZIbC
8m9iSavgLBV3rjjLWlJA6If0mQB2AG9Tdqwx8DEZ2JkApFEV/3cVHBHZAsEAKQaN
sgiaN9kTAAABc2xnnNUAAAQDAEcwRQIgEPaNEnqPmcpDQ3cN99LaDKx+vFw6jfeS
OSQBrcNvUE8CIQDLfDhyvPeo17jINiQ2/tOsdTBe2sfG/edUUdPNjJCvTDAdBgNV
HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwggHBBgNVHSAEggG4MIIBtDCCAZwG
DysGAQQBgagYAgEBgSoCDjCCAYcwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcC5lLXN6
aWduby5odS9xY3BzMHgGCCsGAQUFBwICMGwMalF1YWxpZmllZCBQU0QyIGNlcnRp
ZmljYXRlIGZvciB3ZWJzaXRlIGF1dGhlbnRpY2F0aW9uLiBUaGUgY2VydGlmaWNh
dGUgaXMgYXNzb2NpYXRlZCB3aXRoIGFuIG9yZ2FuaXphdGlvbi4wMwYIKwYBBQUH
AgIwJwwlRXh0ZW5kZWQgVmFsaWRhdGlvbiAoRVYpIGNlcnRpZmljYXRlLjBxBggr
BgEFBQcCAjBlDGNNaW7FkXPDrXRldHQgUFNEMiB3ZWJvbGRhbC1oaXRlbGVzw610
xZEgdGFuw7pzw610dsOhbnkuIEEgdGFuw7pzw610dsOhbnkgc3plcnZlemV0aGV6
IGthcGNzb2zDs2Rpay4wOwYIKwYBBQUHAgIwLwwtRm9rb3pvdHRhbiBlbGxlbsWR
cnrDtnR0IChFVikgdGFuw7pzw610dsOhbnkuMAkGBwQAgZgnAwEwBwYFZ4EMAQEw
HQYDVR0OBBYEFIfrVZNYH1DL4kVfimcjnAtGyIjpMB8GA1UdIwQYMBaAFH2ETsLU
a+rB1yKMaMPpoPTsmIocMEIGA1UdEQQ7MDmCEWVuYWJsZWJhbmtpbmcuY29tggp0
aWxpc3kuY29tghh0aWxpc3kuZW5hYmxlYmFua2luZy5jb20wgbYGA1UdHwSBrjCB
qzA3oDWgM4YxaHR0cDovL3F0bHNjYTIwMTgtY3JsMS5lLXN6aWduby5odS9xdGxz
Y2EyMDE4LmNybDA3oDWgM4YxaHR0cDovL3F0bHNjYTIwMTgtY3JsMi5lLXN6aWdu
by5odS9xdGxzY2EyMDE4LmNybDA3oDWgM4YxaHR0cDovL3F0bHNjYTIwMTgtY3Js
My5lLXN6aWduby5odS9xdGxzY2EyMDE4LmNybDCCAV8GCCsGAQUFBwEBBIIBUTCC
AU0wLwYIKwYBBQUHMAGGI2h0dHA6Ly9xdGxzY2EyMDE4LW9jc3AxLmUtc3ppZ25v
Lmh1MC8GCCsGAQUFBzABhiNodHRwOi8vcXRsc2NhMjAxOC1vY3NwMi5lLXN6aWdu
by5odTAvBggrBgEFBQcwAYYjaHR0cDovL3F0bHNjYTIwMTgtb2NzcDMuZS1zemln
bm8uaHUwPAYIKwYBBQUHMAKGMGh0dHA6Ly9xdGxzY2EyMDE4LWNhMS5lLXN6aWdu
by5odS9xdGxzY2EyMDE4LmNydDA8BggrBgEFBQcwAoYwaHR0cDovL3F0bHNjYTIw
MTgtY2EyLmUtc3ppZ25vLmh1L3F0bHNjYTIwMTguY3J0MDwGCCsGAQUFBzAChjBo
dHRwOi8vcXRsc2NhMjAxOC1jYTMuZS1zemlnbm8uaHUvcXRsc2NhMjAxOC5jcnQw
JgYFZ4EMAwEEHTAbEwNQU0QTAkZJDBBGSU5GU0EtMjk4ODQ5OS03MIHmBggrBgEF
BQcBAwSB2TCB1jAIBgYEAI5GAQEwCwYGBACORgEDAgEKMFMGBgQAjkYBBTBJMCQW
Hmh0dHBzOi8vY3AuZS1zemlnbm8uaHUvcWNwc19lbhMCZW4wIRYbaHR0cHM6Ly9j
cC5lLXN6aWduby5odS9xY3BzEwJodTATBgYEAI5GAQYwCQYHBACORgEGAzBTBgYE
AIGYJwIwSTATMBEGBwQAgZgnAQMMBlBTUF9BSQwnRmlubmlzaCBGaW5hbmNpYWwg
U3VwZXJ2aXNvcnkgQXV0aG9yaXR5DAlGSS1GSU5GU0EwDQYJKoZIhvcNAQELBQAD
ggEBAC7bjJ6dmhMQwQCiWLmBvVvS7VTyduwo2TiYokFbcx+Zk74m46hG7u8nc9Hg
P2AkUSTWTsnBeXrsInlUZiIbIHLiAtbvanz34mWtddHYyQnnBjCokn4xPQ9nuMgg
YAXCWuWMwHIqpGTMPeNUelXNCcIzYYjxju6708K0EAB2NfLw/48qPnIApkBeTusg
12TcuwiSnsHYSC1Sa+bzxMjcjnZvY/p+Ise02GXUsoQcoujrsmPZJ4b0Xpo3E0FO
U0XAiG5vMjpeYHt06BTk36ZUzztfhT0ZcTi9doDtUEZYIUZxfzv0kDNGtoAZoQ+k
AGOpy4HAEzfBMTvriQCQeipdpbE=
-----END CERTIFICATE-----
```

Thanks in advance!

**Comment by hoeg** [comment]
Hi @Agachily I have released a fix that should make it possible for you to register now. Please try again and let me know if you are experiencing any issues with the registration.

**Comment by Agachily** [comment]
@hoeg Thanks very much for your help! But I still can not register with our certificate. The error is same. The response of my request is as follows:
```
*   Trying 54.229.44.47:443...
* Connected to openbanking.prod.lunar.app (54.229.44.47) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Request CERT (13):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Certificate (11):
* (304) (OUT), TLS handshake, CERT verify (15):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=openbanking.prod.lunar.app
*  start date: Apr 12 05:17:36 2022 GMT
*  expire date: Jul 11 05:17:35 2022 GMT
*  subjectAltName: host "openbanking.prod.lunar.app" matched cert's "openbanking.prod.lunar.app"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fbefc011a00)
> POST /tpp/register HTTP/2
> Host: openbanking.prod.lunar.app
> user-agent: curl/7.79.1
> accept: */*
> x-request-id: C14995F9-1044-4426-9B57-F3431BEA29A9
> content-type: application/json
> content-length: 96
> 
* We are completely uploaded and fine
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 400 
< date: Thu, 19 May 2022 13:12:59 GMT
< content-type: text/html
< content-length: 208
< 
<html>
<head><title>400 The SSL certificate error</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The SSL certificate error</center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host openbanking.prod.lunar.app left intact
```

**Comment by fed239** [comment]
Hello @hoeg @runehammerskov @eXeDK @mrjensen  @mahlunar @Crevil could you please help us to resolve the issue? 🙏 

Many thanks in advance!

**Comment by Agachily** [comment]
Hi, I have tried again with our new certificate, but still encounter the  `400 The SSL certificate error` problem. The new cert I used is as follows:

```
-----BEGIN CERTIFICATE-----
MIIK7zCCCdegAwIBAgIOAff4XUuF8vB09gTFtAowDQYJKoZIhvcNAQELBQAwejEL
MAkGA1UEBhMCSFUxETAPBgNVBAcMCEJ1ZGFwZXN0MRYwFAYDVQQKDA1NaWNyb3Nl
YyBMdGQuMRcwFQYDVQRhDA5WQVRIVS0yMzU4NDQ5NzEnMCUGA1UEAwweUXVhbGlm
aWVkIGUtU3ppZ25vIFRMUyBDQSAyMDE4MB4XDTIyMDUyMDEwMjc1NloXDTIzMDUy
MDEwMjc1Nlowgb4xEzARBgsrBgEEAYI3PAIBAxMCRkkxHTAbBgNVBA8MFFByaXZh
dGUgT3JnYW5pemF0aW9uMRIwEAYDVQQFEwkyOTg4NDk5LTcxCzAJBgNVBAYTAkZJ
MQ4wDAYDVQQHDAVFc3BvbzEaMBgGA1UECgwRRW5hYmxlIEJhbmtpbmcgT3kxHzAd
BgNVBGEMFlBTREZJLUZJTkZTQS0yOTg4NDk5LTcxGjAYBgNVBAMMEWVuYWJsZWJh
bmtpbmcuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAscnbTyQn
hEDKr+zPUw5qVBWr+R+uCYVlVAQDULCRs6xvK3sk1ClFVe5OvkclG11EcTPqrx64
KXDzb8mYezfr3NORXA83yaleWIf9p1/RbdK7fpRqmP6WP4gicZFRmZzGe5wLBSll
sieBVMxT3OGP4OomV4ewv6grIzry/C4wrdw3swPZMC4T49f+6Tj4yV+/zKRUH8jw
/PaJl5tS6yTZzQCtPsf1jJnllIdYP9sl/usnU9aLdDTXcbJmBTUN+j3HB2MIEDtf
xorV5RtF5kmAacjlsyIrTZStymVXvLhB2c/qm2PxRWBrWs6o8Z3cBWGsFXlpkSa4
qME7h82heyR3KwIDAQABo4IHLDCCBygwDgYDVR0PAQH/BAQDAgWgMIIBfwYKKwYB
BAHWeQIEAgSCAW8EggFrAWkAdgDoPtDaPvUGNTLnVyi8iWvJA9PL0RFr7Otp4Xd9
bQa9bgAAAYDhAoEtAAAEAwBHMEUCIH7XImEfMq82FIIAMPUn/G6WqDzDyStbej+B
wQOxbIc9AiEA3f/xeWh081lQO6FQ9BnCxLJTLks48I9mEZVGBiXp/zcAdgBVgdTC
FpA2AUrqC5tXPFPwwOQ4eHAlCBcvo6odBxPTDAAAAYDhAqA9AAAEAwBHMEUCIEh9
7qtnNPclialxEXbaTHBQyv0wl8qBQwaRyIoTfyRVAiEAhipVGo76lxPY7F+/gIfB
F/zGKtjYqXpeR5Px8uCfP4YAdwB6MoxU2LcttiDqOOBSHumEFnAyE4VNO9IrwTpX
o1LrUgAAAYDhAqQtAAAEAwBIMEYCIQDmq1KpRRrlHBPAycDrqUVfZf7yR9iyRybY
AMUGYe+t9AIhAP4s06k9imaAxWPnHEc1SAzkGHsmrxs1lvyXoBFfNc4XMB0GA1Ud
JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATCCAcEGA1UdIASCAbgwggG0MIIBnAYP
KwYBBAGBqBgCAQGBKgIZMIIBhzAmBggrBgEFBQcCARYaaHR0cDovL2NwLmUtc3pp
Z25vLmh1L3FjcHMweAYIKwYBBQUHAgIwbAxqUXVhbGlmaWVkIFBTRDIgY2VydGlm
aWNhdGUgZm9yIHdlYnNpdGUgYXV0aGVudGljYXRpb24uIFRoZSBjZXJ0aWZpY2F0
ZSBpcyBhc3NvY2lhdGVkIHdpdGggYW4gb3JnYW5pemF0aW9uLjAzBggrBgEFBQcC
AjAnDCVFeHRlbmRlZCBWYWxpZGF0aW9uIChFVikgY2VydGlmaWNhdGUuMHEGCCsG
AQUFBwICMGUMY01pbsWRc8OtdGV0dCBQU0QyIHdlYm9sZGFsLWhpdGVsZXPDrXTF
kSB0YW7DunPDrXR2w6FueS4gQSB0YW7DunPDrXR2w6FueSBzemVydmV6ZXRoZXog
a2FwY3NvbMOzZGlrLjA7BggrBgEFBQcCAjAvDC1Gb2tvem90dGFuIGVsbGVuxZFy
esO2dHQgKEVWKSB0YW7DunPDrXR2w6FueS4wCQYHBACBmCcDATAHBgVngQwBATAd
BgNVHQ4EFgQUh+tVk1gfUMviRV+KZyOcC0bIiOkwHwYDVR0jBBgwFoAUfYROwtRr
6sHXIoxow+mg9OyYihwwQgYDVR0RBDswOYIRZW5hYmxlYmFua2luZy5jb22CCnRp
bGlzeS5jb22CGHRpbGlzeS5lbmFibGViYW5raW5nLmNvbTCBtgYDVR0fBIGuMIGr
MDegNaAzhjFodHRwOi8vcXRsc2NhMjAxOC1jcmwxLmUtc3ppZ25vLmh1L3F0bHNj
YTIwMTguY3JsMDegNaAzhjFodHRwOi8vcXRsc2NhMjAxOC1jcmwyLmUtc3ppZ25v
Lmh1L3F0bHNjYTIwMTguY3JsMDegNaAzhjFodHRwOi8vcXRsc2NhMjAxOC1jcmwz
LmUtc3ppZ25vLmh1L3F0bHNjYTIwMTguY3JsMIIBXwYIKwYBBQUHAQEEggFRMIIB
TTAvBggrBgEFBQcwAYYjaHR0cDovL3F0bHNjYTIwMTgtb2NzcDEuZS1zemlnbm8u
aHUwLwYIKwYBBQUHMAGGI2h0dHA6Ly9xdGxzY2EyMDE4LW9jc3AyLmUtc3ppZ25v
Lmh1MC8GCCsGAQUFBzABhiNodHRwOi8vcXRsc2NhMjAxOC1vY3NwMy5lLXN6aWdu
by5odTA8BggrBgEFBQcwAoYwaHR0cDovL3F0bHNjYTIwMTgtY2ExLmUtc3ppZ25v
Lmh1L3F0bHNjYTIwMTguY3J0MDwGCCsGAQUFBzAChjBodHRwOi8vcXRsc2NhMjAx
OC1jYTIuZS1zemlnbm8uaHUvcXRsc2NhMjAxOC5jcnQwPAYIKwYBBQUHMAKGMGh0
dHA6Ly9xdGxzY2EyMDE4LWNhMy5lLXN6aWduby5odS9xdGxzY2EyMDE4LmNydDAm
BgVngQwDAQQdMBsTA1BTRBMCRkkMEEZJTkZTQS0yOTg4NDk5LTcwgeYGCCsGAQUF
BwEDBIHZMIHWMAgGBgQAjkYBATALBgYEAI5GAQMCAQowUwYGBACORgEFMEkwJBYe
aHR0cHM6Ly9jcC5lLXN6aWduby5odS9xY3BzX2VuEwJlbjAhFhtodHRwczovL2Nw
LmUtc3ppZ25vLmh1L3FjcHMTAmh1MBMGBgQAjkYBBjAJBgcEAI5GAQYDMFMGBgQA
gZgnAjBJMBMwEQYHBACBmCcBAwwGUFNQX0FJDCdGaW5uaXNoIEZpbmFuY2lhbCBT
dXBlcnZpc29yeSBBdXRob3JpdHkMCUZJLUZJTkZTQTANBgkqhkiG9w0BAQsFAAOC
AQEAff2AhbuD5ZjFpH5px+QxYXfSPbqVELBUyclKfHtgw54qH5plxjjbPbO8aScM
7/5X4Jnl5kdfzjvlWcc6jnS/EdztaxqTeYPbnoXtIn60WFxUta37kETSAtAJ0hVh
bteq0Y9ax3wQ2M/Scl9PjTNzNvi4+Hw4P5u4JzbJTIrU/Il8ro+GJWS3kXF/jFCO
WmT6h7FfZH7IAf5Ma1/FmD2esDeGzugbfFAqSLKqd57wodN9LIVxvCm1N0q4lZVB
sLf0qeRa9/AXTsBKf1RLyeRbiFKJHz1GIlB9sg9tbHpkY6Ak5Y338Lg9bl6u4nFq
SyEq/m589rCFli3/kWlEpA6/VQ==
-----END CERTIFICATE-----
```

**Comment by hoeg** [comment]
Hi @Agachily, we have located an other issue regarding the registration service. I am making a fix as we write!

**Comment by fed239** [comment]
@hoeg thanks a lot for the update, looking forward to testing again next week. have a great weekend!

**Comment by Agachily** [comment]
Thanks for your effort! Thanks very much!

**Comment by fed239** [comment]
@hoeg Do you have any update on the issue? We are still very eager to get started in the live environment :) TY!

**Comment by hoeg** [comment]
Hi @fed239, unfortunately this is an issue in an upstream project so we have to get a new release for that before we can have a fix ready. Unfortunately I do not have any timeline for when that happens.

**Comment by Agachily** [comment]
Thanks very much!

**Comment by Agachily** [comment]
Hi, @hoeg! I still encountered this issue? Do you have any suggestions for this, thanks!

**Comment by fed239** [comment]
This worked with chained certificate
